### ISSUE TITLE
Queue drag and drop not working in Safari

### ISSUE THREAD

**Issue by suprasanna** [bufferapp/buffer-publish#235]
Using Safari on OS X, dragging posts in the queue isn't working. If I click, hold and drag, the post seems to flicker but doesn't actually move. Tried to capture it here in the screencast:

http://hi.buffer.com/0B2B1x2T0I0f

**Comment by hamstu** [comment]
@suprasanna You can't drag those posts because they have _no time set_. Is your queue paused and/or do you have days in your schedule?

Also, in the event that this happens to customers do you think it might be good to explain what's happening so they're not wondering why they can't drag? Related: see the subpoint of **"Pinned and scheduled posts aren’t visually distinct from other posts."** [near the bottom of this Paper doc](https://paper.dropbox.com/doc/Buffer-Publish-New-Dash-stop-and-hammer-GjWxGCMqmBzcsR0OykmbT).

**Comment by suprasanna** [comment]
Ah didn't notice that there @hamstu thank you, yeah the schedule is paused. 

I do think that it'd be good to somehow let the user know! What do you think the best way here might be? 

One potential solution is if the user clicks and holds on a post that can't be dragged (whether due to pinned or no time or something else), we could wait until the move their cursor with it held down and then show an error with our notification style that says something like "Sorry! This post can't be moved in its current state." 

We could go even further and make that message customized to the 'why' (ex. "Sorry! We can't move this post because it needs a time first.") depending on how much work that might be.

Would love your thoughts :)

**Comment by hamstu** [comment]
@suprasanna Yep, that's very doable to show a notification like that. Do you want to riff on the copy for the different states?

1. Post is pinned
2. Post is scheduled 
3. Post has no time (because queue is paused)
4. Post has no time (queue is not paused, so pretty safe to assume no times are in the schedule)

**Comment by suprasanna** [comment]
1. "Sorry, we can't move this post because it's currently pinned!"
2. "Sorry, you can't drag this post because it's currently scheduled for a specific time!"
3. "Sorry, please unpause your queue to drag and drop this post!"
4. "Sorry, your schedule needs some times added before this post can be moved!"

:)

**Comment by suprasanna** [comment]
FYI, lower prio on this one than the TP/Drafts work if that helps triage!

**Comment by hamstu** [comment]
Hey @suprasanna! Gonna close this issue; let's triage/plan this in Jira.
